const fs=require('fs');
const load=f=>Object.fromEntries(fs.readFileSync(f,'utf8').split('\n').filter(l=>l.includes('=')).map(l=>{const i=l.indexOf('=');return[l.slice(0,i).trim(),l.slice(i+1).trim()];}));
const env=load('.env.local'),sec=load('.secrets.local');for(const[k,v]of Object.entries(env))process.env[k]=v;
const{supabase,accountsApi}=require('./app.headless.cjs');
const rp=n=>Math.round(Number(n||0)).toLocaleString('id-ID');
(async()=>{
const{data:auth}=await supabase.auth.signInWithPassword({email:sec.APP_EMAIL,password:sec.APP_PASSWORD});const uid=auth.user.id;
const accounts=await accountsApi.getAll(uid);const nm=id=>accounts.find(a=>a.id===id)?.name||'∅';
const{data:srcs}=await supabase.from('income_sources').select('id,name').eq('user_id',uid);
const sname=id=>(srcs||[]).find(s=>s.id===id)?.name||'(tanpa source)';
console.log('=== kandidat reimburse_in ~745rb–750rb Maret ===');
const{data:h}=await supabase.from('ledger').select('*').eq('user_id',uid).gte('tx_date','2026-03-01').lte('tx_date','2026-03-31').gte('amount_idr',735000).lte('amount_idr',760000);
for(const r of h||[])console.log(`  ${r.tx_date} ${rp(r.amount_idr)} ${r.tx_type} ${r.tx_type==='income'?'src='+sname(r.from_id):nm(r.from_id)}→${nm(r.to_id)} entity=${r.entity||'-'} kat=${r.category_name||'-'}\n     ${r.description}`);
console.log('\n=== struktur reimburse_in yang sudah ada (pajak mama) ===');
const{data:p}=await supabase.from('ledger').select('*').eq('user_id',uid).eq('tx_type','reimburse_in').gte('amount_idr',2385000).lte('amount_idr',2386500).limit(2);
for(const r of p||[])console.log(' ',JSON.stringify(Object.fromEntries(Object.entries(r).filter(([k,v])=>v!==null&&!['user_id','id','created_at','updated_at'].includes(k))))); 
console.log('\n=== entity pasangan pajak mama (out & in) ===');
const{data:pm}=await supabase.from('ledger').select('tx_date,tx_type,amount_idr,entity,from_id,to_id,description').eq('user_id',uid).gte('amount_idr',2385000).lte('amount_idr',2386500).order('tx_date');
for(const r of pm||[])console.log(`  ${r.tx_date} ${r.tx_type.padEnd(13)} entity=${(r.entity||'-').padEnd(8)} ${nm(r.from_id)}→${nm(r.to_id)} | ${(r.description||'').slice(0,42)}`);
process.exit(0);})();
